Repository myriadsocial/myriad-api, pull requests merged in 2021-12, with the labels that each got.

#263 fixed timeline query
  src/services/friend.service.ts
Labels: Improvement

#264 Improvement/query
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#267 Fix migration
  src/migrations/1.0.0.migration.ts
Labels: Improvement

#272 empty importers when not friend
  src/services/post.service.ts
Labels: Improvement

#273 fixed post query
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#278 migration for friends collection
  src/migrations/1.0.0.migration.ts
Labels: Improvement

#280 Migration/friends
  src/migrations/1.0.0.migration.ts
  src/services/friend.service.ts
Labels: Improvement

#281 added endpoint for handle draft post
  src/controllers/index.ts
  src/controllers/post.controller.ts
  src/controllers/user-draft-post.controller.ts
Labels: Improvement

#284 recalculate kudos when removed vote
  src/interceptors/validate-vote.interceptor.ts
  src/services/metric.service.ts
Labels: Improvement

#287 fixed timeline query
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
  src/services/friend.service.ts
  src/services/tag.service.ts
Labels: Improvement

#291 fixed primary social media
  src/controllers/user-social-media.controller.ts
  src/services/user-social-media.service.ts
Labels: Improvement

#295 add body size ingress
  .github/workflows/deploy.yml
Labels: CI

#296 Make public for image mutation
  src/services/fcs.service.ts
Labels: Feature

#297 Fixed video upload destination
  src/services/fcs.service.ts
Labels: Fix

#299 Added upload type
  src/controllers/storage.controller.ts
  src/enums/index.ts
  src/enums/upload-type.enum.ts
  src/services/fcs.service.ts
Labels: Feature

#301 added account setting migration
  src/migrations/1.0.0.migration.ts
Labels: Improvement

#306 fixed endpoint delete user experience
  src/interceptors/experience.interceptor.ts
Labels: Improvement

#308 fixed exchange rates
  src/__tests__/helpers/given-instances.ts
  src/__tests__/unit/currency.controller.unit.ts
  src/application.ts
  src/controllers/currency.controller.ts
  src/index.ts
  src/interceptors/validate-currency.interceptor.ts
  src/jobs/update-exchange-rate.job.ts
  src/models/currency.model.ts
Labels: Improvement

#310 fixed post filter by experience & include users in experience
  src/interceptors/experience.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
Labels: Improvement

#307 added cron job for fetching people
  src/application.ts
  src/index.ts
  src/jobs/index.ts
  src/jobs/update-people-profile.job.ts
Labels: Improvement

#311 error handling for coin market cap api
  src/__tests__/helpers/given-instances.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/validate-currency.interceptor.ts
Labels: Improvement

#312 handle unknown myrian and initial migration
  .env-template
  src/__tests__/acceptance/currency.acceptance.ts
  src/__tests__/acceptance/transaction-summary.acceptance.ts
  src/__tests__/acceptance/user-currency.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/config.ts
  src/data-seed/currencies.json
  src/data-seed/users.json
  src/interceptors/pagination.interceptor.ts
  src/migrations/0.0.0.migration.ts
  src/migrations/1.0.0.migration.ts
  src/services/currency.service.ts
  src/services/friend.service.ts
  src/services/notification.service.ts
Labels: Improvement

#313 fixed experiences
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/controllers/user-experience.controller.ts
  src/enums/classname-type.enum.ts
  src/interceptors/experience.interceptor.ts
Labels: Improvement

#315 fixed query
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
  src/services/tag.service.ts
Labels: Improvement

#316 MYR-00: setup container resources
  .github/workflows/deploy.yml
Labels: CI

#317 Improved default config
  src/config.ts
Labels: enhancement

#319 Removed video converter
  package.json
  src/services/fcs.service.ts
  yarn.lock
Labels: Fix

#318 Improve deployment automation
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/test.yml
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
Labels: CI

#321 change deploy workflow_run
  .github/workflows/deploy.yml
Labels: CI

#322 MYR-000: fixed typo and change image tag
  .github/workflows/deploy.yml
Labels: CI

#323 change API DNS
  .github/workflows/deploy.yml
Labels: CI

#324 MYR-000: fix deploy automation
  .github/workflows/deploy.yml
Labels: CI

#325 Fixed typo for firebase env
  .env-template
  src/application.ts
  src/config.ts
  src/controllers/storage.controller.ts
Labels: Fix

#326 Add new env and improve tag logic
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
Labels: CI

#327 Fix create pre-release draft
  .github/workflows/builder.yml
Labels: CI

#328 fixed query
  src/interceptors/pagination.interceptor.ts
  src/models/user.model.ts
Labels: Improvement

#329 Improve image tag development
  .github/workflows/deploy.yml
Labels: CI

#330 added new endpoint for notifaction to mark read multiple notification
  src/controllers/notification.controller.ts
Labels: Improvement

#331 Sentry ignore option on initialize
  .env-template
  package.json
  src/application.ts
  src/config.ts
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: Feature

#332 handle blocked user response
  src/__tests__/acceptance/post.acceptance.ts
  src/interceptors/deleted-document.interceptor.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/models/post.model.ts
  src/services/post.service.ts
Labels: Improvement

#333 Remove transaction with DOT as currency
  src/migrations/1.0.0.migration.ts
Labels: Improvement

#334 Format image with metadata
  src/services/fcs.service.ts
Labels: enhancement

#335 Removed upvote downvote from notification
  src/controllers/vote.controller.ts
  src/migrations/1.0.0.migration.ts
Labels: Improvement

#336 added additional referenceId when dis/connecting socialmedia
  src/controllers/user-social-media.controller.ts
  src/services/notification.service.ts
Labels: Improvement

#337 Added logger to controller
  src/application.ts
  src/config.ts
  src/controllers/activity-log.controller.ts
  src/controllers/authentication.controller.ts
  src/controllers/comment.controller.ts
  src/controllers/currency.controller.ts
  src/controllers/deleted-collection.controller.ts
  src/controllers/exchange-rate.controller.ts
  src/controllers/experience.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/leader-board.controller.ts
  src/controllers/notification.controller.ts
  src/controllers/people.controller.ts
  src/controllers/post-walletaddress.controller.ts
  src/controllers/post.controller.ts
  src/controllers/queue.controller.ts
  src/controllers/report-user.controller.ts
  src/controllers/report.controller.ts
  src/controllers/storage.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tip.controller.ts
  src/controllers/transaction-summary.controller.ts
  src/controllers/transaction.controller.ts
  src/controllers/user-account-setting.controller.ts
  src/controllers/user-currency.controller.ts
  src/controllers/user-draft-post.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/user-notification-setting.controller.ts
  src/controllers/user-report.controller.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/user.controller.ts
  src/controllers/vote.controller.ts
  src/index.ts
Labels: enhancement

#338 Fixed imported post response
  src/services/post.service.ts
Labels: Improvement

#339 Added migration for dis/connected social media
  src/migrations/1.0.0.migration.ts
Labels: Improvement
