Repository myriadsocial/myriad-api, pull requests merged in 2021-10, with the labels that each got.

#174 Unhiding password from response
  src/__tests__/integration/controllers/user.controller.integration.ts
  src/models/user.model.ts
Labels: bug

#181 CI/CD: added sentry node
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#183 CI: Updated reward amount
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
Labels: CI

#184 CI: implement new flow
  .eslintignore
  LICENSE
  package.json
Labels: CI

#187 Added new filter for search post
  src/interceptors/pagination.interceptor.ts
Labels: Improvement
