Repository myriadsocial/myriad-api, pull requests merged in 2022-08, with the labels that each got.

#617 feat: set notification for data only
  src/services/fcm.service.ts
  src/services/notification.service.ts
Labels: enhancement

#618 fix: fcm payload
  src/services/fcm.service.ts
Labels: Fix

#619 fix: failed to import reddit post with multiple images
  package.json
  public/index.html
  src/services/social-media.service.ts
Labels: Improvement

#620 fix: handle cancel friend request from requestor
  src/interceptors/authorize.interceptor.ts
Labels: Improvement

#621 feat: notification for admin
  package.json
  public/index.html
  src/enums/notification-type.enum.ts
  src/interceptors/create.interceptor.ts
  src/services/notification.service.ts
Labels: Feature, Improvement

#622 fix: improve near auth security
  package.json
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/utils/near-api-js.ts
  src/utils/polkadotJs-utils.ts
  src/utils/validate-account.ts
  yarn.lock
Labels: Improvement

#623 chore: bump version to 2.1.12
  package.json
  public/index.html
Labels: Feature

#625 fix: airdrop user onboarding to monthly
  src/interceptors/pagination.interceptor.ts
Labels: Fix

#626 fix: added new field walletURL in network document
  src/models/network.model.ts
Labels: Improvement

#627 fix: renamed walletURL
  src/models/network.model.ts
Labels: Improvement
