Repository myriadsocial/myriad-api, pull requests merged in 2022-10, with the labels that each got.

#648 fix: added friend info for 'add friend' button on friends tab and sea…
  src/interceptors/pagination.interceptor.ts
  src/services/friend.service.ts
Labels: Improvement

#649 fix: added new data for server metric
  src/__tests__/unit/currency.controller.unit.ts
  src/controllers/currency.controller.ts
  src/interceptors/pagination.interceptor.ts
  src/interfaces/metric.interface.ts
  src/services/metric.service.ts
Labels: Improvement

#650 fix: user growth stats
  src/__tests__/unit/currency.controller.unit.ts
  src/controllers/currency.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/index.ts
  src/controllers/statistic.controller.ts
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#661 fix: change storage endpoint to general endpoint
  src/controllers/storage.controller.ts
  src/interceptors/authorize.interceptor.ts
Labels: Improvement

#662 fix: improve GET /friends security
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/user.acceptance.ts
  src/__tests__/integration/controllers/friend.controller.integration.ts
  src/__tests__/unit/friend.controller.unit.ts
  src/controllers/friend.controller.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/authentication/jwt.service.ts
Labels: Improvement

#663 feat: auth email and personal access token
  .env-template
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  package.json
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/config.ts
  src/controllers/authentication.controller.ts
  src/controllers/index.ts
  src/controllers/user-personal-access-token.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/models/email-template.model.ts
  src/models/index.ts
  src/models/request-create-new-user-by-email.model.ts
  src/models/request-create-new-user-by-wallet.model.ts
  src/models/request-create-new-user.model.ts
  src/models/request-login-by-email.model.ts
  src/models/request-otpw.model.ts
  src/models/user-otpw.model.ts
  src/models/user-personal-access-token.model.ts
  src/models/user-wallet.model.ts
  src/models/user.model.ts
  src/repositories/index.ts
  src/repositories/user-otpw.repository.ts
  src/repositories/user-personal-access-token.repository.ts
  src/services/email.service.ts
  src/services/index.ts
  yarn.lock
Labels: Feature

#665 refactor: Auth email and OTP format
  public/index.html
  src/config.ts
  src/controllers/authentication.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/index.ts
  src/models/request-login-by-email.model.ts
  src/models/request-login-by-otp.model.ts
  src/models/request-otp-by-email.model.ts
  src/models/request-otpw.model.ts
  src/models/user-otp.model.ts
  src/repositories/index.ts
  src/repositories/user-otp.repository.ts
  src/services/email.service.ts
  src/services/index.ts
  src/services/user-otp.service.ts
  src/utils/near-api-js.ts
  src/utils/validate-account.ts
Labels: Improvement

#668 fix: rate limit proxy ip and email template
  .env-template
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  src/__tests__/acceptance/currency.acceptance.ts
  src/__tests__/acceptance/people.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/__tests__/unit/currency.controller.unit.ts
  src/application.ts
  src/config.ts
  src/index.ts
  src/sequence.ts
  src/services/email.service.ts
  src/services/social-media.service.ts
Labels: Fix

#669 fix: authentication with near
  package.json
  src/interceptors/authentication.interceptor.ts
  src/models/server.model.ts
  src/utils/near-api-js.ts
Labels: Improvement

#671 fix: check user by email
  src/controllers/authentication.controller.ts
  src/interceptors/find-by-id.interceptor.ts
Labels: Improvement
