Repository myriadsocial/myriad-api, pull requests merged in 2022-02, with the labels that each got.

#400 Fixed experience timeline
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
Labels: Improvement

#401 Fixed decline friend request
  src/interceptors/authorize.interceptor.ts
Labels: Fix

#402 Enabled auth for search people
  src/controllers/people.controller.ts
Labels: Fix

#403 Fixed search by hashtags
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#404 Fixed search experience
  src/controllers/experience.controller.ts
Labels: Improvement

#406 Fixed import post
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/social-media.service.ts
Labels: Improvement

#407 Fixed mention notification
  src/services/notification.service.ts
Labels: Improvement

#409 Fixed post and comment when private account
  src/__tests__/helpers/database.helper.ts
  src/__tests__/unit/post.controller.unit.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
  src/services/post.service.ts
  src/services/tag.service.ts
Labels: Improvement

#410 Fixed minor bugfix
  src/controllers/comment.controller.ts
  src/interceptors/pagination.interceptor.ts
  src/services/post.service.ts
Labels: Improvement

#411 Changed txHash to blockHash when manually claim tips
  src/__tests__/acceptance/post.acceptance.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/services/currency.service.ts
Labels: Improvement

#413 fix minor bug
  src/controllers/comment.controller.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
Labels: Improvement

#414 Fixed authorize interceptor
  src/__tests__/acceptance/friend.acceptance.ts
  src/interceptors/authorize.interceptor.ts
Labels: Improvement

#415 Fixed migration storage url
  src/application.ts
Labels: Fix

#416 Improved search post query
  package.json
  public/index.html
  src/__tests__/acceptance/post.acceptance.ts
  src/application.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/models/draft-post.model.ts
  src/models/post.model.ts
  src/services/post.service.ts
  src/services/social-media.service.ts
  yarn.lock
Labels: Improvement

#420 Fixed dependencies
  src/application.ts
Labels: Improvement

#418 Counter should follow current posts
  src/__tests__/acceptance/post.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/__tests__/unit/post.controller.unit.ts
  src/controllers/post.controller.ts
  src/interceptors/delete.interceptor.ts
  src/services/metric.service.ts
  src/services/post.service.ts
  src/services/tag.service.ts
Labels: Improvement

#421 Fixed migration
  src/application.ts
Labels: Improvement

#419 Implement admin permission
  src/__tests__/acceptance/currency.acceptance.ts
  src/__tests__/acceptance/people.acceptance.ts
  src/__tests__/acceptance/report.acceptance.ts
  src/__tests__/acceptance/tag.acceptance.ts
  src/application.ts
  src/controllers/activity-log.controller.ts
  src/controllers/admin.controller.ts
  src/controllers/authentication.controller.ts
  src/controllers/comment.controller.ts
  src/controllers/currency.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/index.ts
  src/controllers/notification.controller.ts
  src/controllers/people.controller.ts
  src/controllers/post.controller.ts
  src/controllers/report.controller.ts
  src/controllers/storage.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tip.controller.ts
  src/controllers/transaction.controller.ts
  src/controllers/user-account-setting.controller.ts
  src/controllers/user-currency.controller.ts
  src/controllers/user-draft-post.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/user-language-setting.controller.ts
  src/controllers/user-notification-setting.controller.ts
  src/controllers/user-report.controller.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/user.controller.ts
  src/controllers/vote.controller.ts
  src/enums/controller-type.enum.ts
  src/enums/index.ts
  src/enums/method-type.enum.ts
  src/enums/permission-keys.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/authorize.interceptor.ts
  src/interfaces/index.ts
  src/interfaces/required-permissions.interface.ts
  src/models/user.model.ts
  src/services/authentication/jwt.service.ts
Labels: Improvement

#422 Handle for dummy experience
  src/services/experience.service.ts
Labels: Improvement

#423 Fixed create tags
  src/application.ts
  src/controllers/post.controller.ts
  src/interceptors/create.interceptor.ts
  src/services/post.service.ts
  src/services/tag.service.ts
Labels: Improvement

#425 Fixed user currency priority
  src/application.ts
  src/interceptors/pagination.interceptor.ts
  src/services/currency.service.ts
  src/services/social-media.service.ts
Labels: Improvement

#426 Escrow transfer validation
  src/services/authentication/jwt.auth.strategy.ts
  src/services/authentication/jwt.service.ts
  src/services/currency.service.ts
Labels: Improvement

#428 Hotfix duplicate mongo id
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/acceptance/currency.acceptance.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/services/social-media.service.ts
  src/services/tag.service.ts
Labels: Improvement

#429 Fixed user banned notification
  src/services/notification.service.ts
Labels: Improvement

#430 Handle timeline with deletedAt
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/report.interceptor.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/experience.service.ts
  src/services/friend.service.ts
  src/services/post.service.ts
  src/services/tag.service.ts
Labels: Improvement

#431 Handle non latin hashtags
  src/controllers/post.controller.ts
  src/services/post.service.ts
  src/services/tag.service.ts
  src/utils/format-tag.ts
Labels: Improvement

#432 Handle non latin hashtags when formating twitter text
  src/services/social-media.service.ts
  src/utils/format-tag.ts
Labels: Improvement

#433 Handle error when post is deleted by admin
  src/__tests__/acceptance/account-setting.acceptance.ts
  src/__tests__/acceptance/activity-log.acceptance.ts
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/acceptance/comment.acceptance.ts
  src/__tests__/acceptance/currency.acceptance.ts
  src/__tests__/acceptance/experience.acceptance.ts
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/notification-setting.acceptance.ts
  src/__tests__/acceptance/notification.acceptance.ts
  src/__tests__/acceptance/people.acceptance.ts
  src/__tests__/acceptance/post-walletaddress.acceptance.ts
  src/__tests__/acceptance/post.acceptance.ts
  src/__tests__/acceptance/report-user.acceptance.ts
  src/__tests__/acceptance/report.acceptance.ts
  src/__tests__/acceptance/tag.acceptance.ts
  src/__tests__/acceptance/transaction-summary.acceptance.ts
  src/__tests__/acceptance/transaction.acceptance.ts
  src/__tests__/acceptance/user-currency.acceptance.ts
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/__tests__/acceptance/user-report.acceptance.ts
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/__tests__/acceptance/user.acceptance.ts
  src/__tests__/acceptance/vote.acceptance.ts
  src/__tests__/helpers/given-repositories.ts
  src/controllers/post.controller.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
  src/services/friend.service.ts
  src/services/metric.service.ts
  src/services/post.service.ts
  src/services/social-media.service.ts
  src/services/tag.service.ts
Labels: Improvement

#434 Filter most tipped
  src/enums/timelinefilter-type.enum.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interfaces/metric.interface.ts
  src/models/post.model.ts
  src/services/metric.service.ts
Labels: Improvement

#436 Improve delete comment
  src/interceptors/authorize.interceptor.ts
  src/interceptors/delete.interceptor.ts
Labels: Improvement

#437 Fixed status code 500
  src/services/social-media.service.ts
  src/services/tag.service.ts
Labels: Improvement

#438 Fixed timeline
  src/__tests__/acceptance/post.acceptance.ts
  src/services/metric.service.ts
  src/services/post.service.ts
Labels: Improvement

#439 Fixed reported comment notification
  src/__tests__/acceptance/comment.acceptance.ts
  src/services/fcm.service.ts
  src/services/notification.service.ts
Labels: Improvement

#440 Created migration
  src/application.ts
  src/services/user-social-media.service.ts
Labels: Improvement

#441 Fixed swagger
  src/controllers/authentication.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/post.controller.ts
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#442 Fixed timeline related
  src/__tests__/acceptance/report.acceptance.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/experience.interceptor.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/report.interceptor.ts
  src/services/experience.service.ts
  src/services/metric.service.ts
  src/services/post.service.ts
  src/services/tag.service.ts
Labels: Improvement

#443 Improved for handling banned user
  src/__tests__/acceptance/post.acceptance.ts
  src/controllers/post.controller.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/report.interceptor.ts
  src/models/post.model.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/metric.service.ts
Labels: Improvement

#444 Created migration
  src/__tests__/integration/controllers/post.controller.integration.ts
  src/__tests__/unit/post.controller.unit.ts
  src/application.ts
  src/controllers/post.controller.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/models/platform-post.model.ts
  src/services/post.service.ts
Labels: Improvement

#445 Fixed notification
  src/services/notification.service.ts
Labels: Improvement

#449 Fixed importers list
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#447 Refactor notification additional referenceId
  src/__tests__/acceptance/comment.acceptance.ts
  src/application.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/experience.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/models/notification.model.ts
  src/services/notification.service.ts
Labels: Improvement

#450 New field in experience response
  src/__tests__/acceptance/experience.acceptance.ts
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/services/experience.service.ts
Labels: Improvement

#451 Removed subscribe experience when user banned
  src/interceptors/report.interceptor.ts
Labels: Improvement

#446 Implement ratelimit
  .env-template
  package.json
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/__tests__/helpers/setup-application.ts
  src/application.ts
  src/config.ts
  src/controllers/exchange-rate.controller.ts
  src/datasources/exchange-rate.datasource.ts
  src/datasources/index.ts
  src/datasources/redis.datasource.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/find-by-id.interceptor.ts
  src/jobs/update-exchange-rate.job.ts
  src/models/exchange-rate.model.ts
  src/repositories/exchange-rate.repository.ts
  src/sequence.ts
  yarn.lock
Labels: Improvement

#453 Add new deployment ENV
  .github/workflows/deployer.yml
Labels: CI

#454 Fixed exchange rates
  src/controllers/exchange-rate.controller.ts
  src/jobs/update-exchange-rate.job.ts
  src/models/exchange-rate.model.ts
Labels: Improvement

#452 Created new endpoint for search friend
  src/__tests__/acceptance/user.acceptance.ts
  src/__tests__/integration/controllers/friend.controller.integration.ts
  src/__tests__/unit/friend.controller.unit.ts
  src/controllers/friend.controller.ts
  src/controllers/user.controller.ts
  src/enums/method-type.enum.ts
  src/interceptors/pagination.interceptor.ts
  src/services/metric.service.ts
Labels: Improvement

#456 Changed user response
  src/interceptors/pagination.interceptor.ts
  src/services/authentication/jwt.auth.strategy.ts
Labels: Improvement

#459 Fixed embedded description
  src/services/social-media.service.ts
Labels: Improvement

#458 Improved autoclaim tips and initial reward
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/services/currency.service.ts
Labels: Improvement

#460 Claimed myriad only
  src/services/currency.service.ts
Labels: Improvement

#461 Fixed embedded
  src/services/social-media.service.ts
Labels: Improvement

#462 Fixed search friend by symbol
  src/interceptors/pagination.interceptor.ts
Labels: Improvement
