Repository myriadsocial/myriad-api, pull requests merged in 2022-05, with the labels that each got.

#535 Trending experience
  src/__tests__/acceptance/report.acceptance.ts
  src/__tests__/unit/vote.controller.unit.ts
  src/application.ts
  src/controllers/post.controller.ts
  src/controllers/report.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/vote.controller.ts
  src/enums/method-type.enum.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/experience.interceptor.ts
  src/interceptors/index.ts
  src/interceptors/update.interceptor.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/models/experience.model.ts
  src/services/experience.service.ts
  src/services/index.ts
  src/services/report.service.ts
Labels: Feature, Improvement

#531 Refactor wallet
  .eslintignore
  .eslintrc.js
  seed-data/default-network-currencies.json
  seed-data/default-user-wallet.json
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/acceptance/user-wallet.acceptance.ts
  src/__tests__/acceptance/user.acceptance.ts
  src/__tests__/acceptance/walletaddress.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/controllers/authentication.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/vote.controller.ts
  src/controllers/walletaddress.controller.ts
  src/enums/index.ts
  src/enums/wallet-type.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/credential.model.ts
  src/models/network.model.ts
  src/models/user-wallet.model.ts
  src/models/user.model.ts
  src/models/wallet.model.ts
  src/services/currency.service.ts
  src/services/experience.service.ts
  src/services/network.service.ts
  src/utils/validate-account.ts
Labels: Improvement

#537 Fixed experience filter
  src/services/experience.service.ts
Labels: Improvement

#539 Added new field in additionalReferenceId
  src/services/notification.service.ts
Labels: Improvement

#532 Prioritize friend to be on top of list
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/user.acceptance.ts
  src/enums/timelinefilter-type.enum.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/user.model.ts
Labels: Improvement

#540 Fixed mention notification
  src/services/notification.service.ts
Labels: Improvement

#541 Fixed user currency creation
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/services/currency.service.ts
Labels: Improvement

#538 Create endpoint for server info
  src/__tests__/helpers/database.helper.ts
  src/application.ts
  src/controllers/server.controller.ts
  src/enums/controller-type.enum.ts
  src/enums/method-type.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/models/index.ts
  src/models/server.model.ts
  src/repositories/index.ts
  src/repositories/server.repository.ts
  src/services/metric.service.ts
Labels: Improvement

#542 Added new endpoint for batch creation experience post
  src/__tests__/acceptance/experience-post.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/__tests__/helpers/given-repositories.ts
  src/controllers/experience-post.controller.ts
  src/enums/method-type.enum.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/services/experience.service.ts
Labels: Improvement

#543 Fixed experience filter
  src/__tests__/acceptance/experience.acceptance.ts
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#544 Fixed experience when deleting
  src/__tests__/acceptance/post.acceptance.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/post.service.ts
Labels: Improvement

#545 Update version
  package.json
  public/index.html
Labels: Improvement

#546 Added filter by user when fetch transaction
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#548 Updated version to 2.1.1
  package.json
  public/index.html
Labels: Improvement

#549 Fixed filter when fetch transaction
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#550 Expose API URLs for Testnet and Mainnet
  .github/workflows/deployer.yml
Labels: CI

#551 Fixed query post by hashtag
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#552 Fixed authentication when login with polkadot js
  src/utils/validate-account.ts
Labels: Improvement

#554 Fixed query post by hashtag in experience timeline
  src/services/experience.service.ts
Labels: Improvement

#553 Remove claim reference from API
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/wallet.controller.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/currency.service.ts
  src/services/network.service.ts
  src/services/user-social-media.service.ts
Labels: Improvement

#556 Fixed connected social media and account
  src/__tests__/acceptance/user-wallet.acceptance.ts
  src/controllers/user-social-media.controller.ts
  src/interceptors/create.interceptor.ts
  src/models/user-social-media.model.ts
  src/services/user-social-media.service.ts
Labels: Improvement

#557 Fix metric field name for server info
  src/interceptors/create.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interfaces/metric.interface.ts
  src/models/server.model.ts
  src/services/metric.service.ts
  src/services/social-media.service.ts
Labels: Improvement

#559 Add sleuth webhook
  .github/workflows/deployer.yml
Labels: CI
