Repository myriadsocial/myriad-api, pull requests merged in 2022-04, with the labels that each got.

#490 Fixed migration
  src/application.ts
Labels: Improvement

#491 Fixed login
  src/__tests__/acceptance/authentication.acceptance.ts
  src/interceptors/authentication.interceptor.ts
Labels: Improvement

#492 Manage currency feature
  src/__tests__/acceptance/currency.acceptance.ts
  src/__tests__/acceptance/transaction.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/__tests__/helpers/given-instances.ts
  src/__tests__/helpers/given-repositories.ts
  src/__tests__/unit/currency.controller.unit.ts
  src/controllers/currency.controller.ts
  src/controllers/index.ts
  src/controllers/transaction.controller.ts
  src/controllers/user-currency.controller.ts
  src/controllers/wallet.controller.ts
  src/enums/controller-type.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/currency.model.ts
  src/models/index.ts
  src/models/network.model.ts
  src/models/transaction.model.ts
  src/models/user-currency.model.ts
  src/models/user.model.ts
  src/repositories/index.ts
  src/repositories/user-currency.repository.ts
  src/repositories/user.repository.ts
  src/services/metric.service.ts
  src/services/network.service.ts
Labels: Feature, Improvement

#495 Fixed user currency
  src/controllers/wallet.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/services/currency.service.ts
Labels: Improvement

#497 Updated migration
  src/application.ts
  src/models/currency.model.ts
Labels: Improvement

#498 Fixed transaction query
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#496 Improved verify socialmedia
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/controllers/user-social-media.controller.ts
  src/interceptors/authorize.interceptor.ts
  src/models/user-verification.model.ts
  src/services/social-media.service.ts
Labels: Improvement

#499 Add new env
  .github/workflows/deployer.yml
Labels: CI

#500 Created server controller
  src/controllers/index.ts
  src/controllers/server.controller.ts
Labels: Improvement

#501 Added new field in network model
  src/application.ts
  src/models/network.model.ts
Labels: Improvement

#502 add docker build args
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .maintain/docker/Dockerfile
Labels: CI

#503 fix helm install command
  .github/workflows/deployer.yml
Labels: CI

#504 Fixed validate near address
  src/application.ts
  src/interceptors/authentication.interceptor.ts
Labels: Improvement

#505 Fixed validate nearAddress
  src/interceptors/authentication.interceptor.ts
Labels: Improvement

#506 Revert "add docker build args"
  .github/workflows/builder.yml
  .maintain/docker/Dockerfile
Labels: CI

#508 Remove unused env
  .env-template
  src/application.ts
  src/config.ts
  src/services/network.service.ts
Labels: Improvement

#509 Fixed claim reference when verify social media
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/controllers/user-social-media.controller.ts
  src/interceptors/create.interceptor.ts
Labels: Improvement

#507 remove unused env
  .github/workflows/deployer.yml
Labels: CI

#510 Fixed network model
  src/models/network.model.ts
  src/services/network.service.ts
  src/utils/formated-balance.ts
Labels: Improvement

#511 Added new endpoint to get wallet address
  src/__tests__/acceptance/user-wallet.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/controllers/index.ts
  src/controllers/post-walletaddress.controller.ts
  src/controllers/walletaddress.controller.ts
  src/enums/network-type.enum.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/models/credential.model.ts
  src/models/user-wallet.model.ts
  src/models/wallet.model.ts
Labels: Improvement

#514 Fixed claim reference when connect to social media
  src/enums/reference-type.enum.ts
  src/interceptors/create.interceptor.ts
  src/services/network.service.ts
Labels: Improvement

#515 remove unused env
  .github/workflows/deployer.yml
Labels: CI

#517 Fixed migration
  src/application.ts
Labels: Improvement

#518 Added new transaction endpoint
  src/__tests__/integration/controllers/transaction.controller.integration.ts
  src/__tests__/unit/transaction.controller.unit.ts
  src/controllers/transaction.controller.ts
  src/interceptors/authorize.interceptor.ts
Labels: Improvement

#519 Update version
  .husky/pre-push
  package.json
  public/index.html
  src/application.ts
Labels: Improvement

#520 Fixed experience counter
  src/interceptors/experience.interceptor.ts
Labels: Improvement

#521 Experience interceptor clean code
  .github/workflows/mlc_config.json
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/interceptors/experience.interceptor.ts
Labels: Improvement

#522 Include network in wallet model
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/acceptance/post-walletaddress.acceptance.ts
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/__tests__/acceptance/user-wallet.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/__tests__/helpers/given-instances.ts
  src/controllers/index.ts
  src/controllers/wallet-network.controller.ts
  src/controllers/wallet.controller.ts
  src/controllers/walletaddress.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/wallet.model.ts
  src/repositories/wallet.repository.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/friend.service.ts
Labels: Improvement

#525 Fixed experience when unsubscribe
  src/interceptors/experience.interceptor.ts
Labels: Improvement

#526 Fixed login when switch network
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/acceptance/post-walletaddress.acceptance.ts
  src/__tests__/acceptance/user-wallet.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/controllers/walletaddress.controller.ts
  src/enums/index.ts
  src/enums/network-type.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/services/network.service.ts
Labels: Improvement

#528 improve docker build
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
Labels: CI

#524 Allowed local storage when GCS is diabled
  .gitignore
  src/application.ts
  src/controllers/storage.controller.ts
  src/services/fcs.service.ts
Labels: Improvement

#527 Configurable data seed
  .env-template
  .gitignore
  package.json
  public/index.html
  seed-data/assets/myriad.png
  seed-data/default-network-currencies.json
  seed-data/default-user-wallet.json
  src/application.ts
  src/config.ts
  src/controllers/storage.controller.ts
  src/services/fcs.service.ts
  src/utils/upload.ts
Labels: Improvement

#529 Code improvement
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/report.acceptance.ts
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/__tests__/acceptance/vote.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/__tests__/integration/controllers/transaction.controller.integration.ts
  src/__tests__/integration/controllers/user-experience.controller.integration.ts
  src/__tests__/integration/controllers/user-social-media.controller.integration.ts
  src/__tests__/unit/post.controller.unit.ts
  src/__tests__/unit/transaction.controller.unit.ts
  src/__tests__/unit/user-experience.unit.ts
  src/__tests__/unit/vote.controller.unit.ts
  src/controllers/report.controller.ts
  src/controllers/transaction.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/user-language-setting.controller.ts
  src/controllers/user-report.controller.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/user-wallet.controller.ts
  src/controllers/vote.controller.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/experience.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/report.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/services/currency.service.ts
  src/services/experience.service.ts
  src/services/metric.service.ts
  src/services/network.service.ts
  src/services/post.service.ts
  src/services/social-media.service.ts
  src/services/tag.service.ts
  src/services/user-social-media.service.ts
Labels: Improvement
