Repository myriadsocial/myriad-api, pull requests merged in 2022-07, with the labels that each got.

#589 fix: notification wording
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/notification.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/__tests__/unit/notification.controller.unit.ts
  src/services/notification.service.ts
Labels: Fix

#591 feat: added experience under post name
  src/__tests__/acceptance/post.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/__tests__/helpers/given-instances.ts
  src/__tests__/unit/post.controller.unit.ts
  src/controllers/index.ts
  src/controllers/post-experience.controller.ts
  src/controllers/post.controller.ts
  src/enums/controller-type.enum.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/models/post.model.ts
  src/repositories/post.repository.ts
  src/services/metric.service.ts
  src/services/post.service.ts
Labels: Feature

#593 fix: new field in server model
  src/application.ts
  src/controllers/server.controller.ts
  src/models/server.model.ts
Labels: Improvement

#592 feat: claim reference
  package.json
  src/controllers/claim-reference.controller.ts
  src/controllers/index.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/user-wallet.controller.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/models/claim-reference.model.ts
  src/models/index.ts
  yarn.lock
Labels: Feature

#594 feat: activate tipping with near
  src/controllers/claim-reference.controller.ts
  src/controllers/user-currency.controller.ts
  src/controllers/walletaddress.controller.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/claim-reference.model.ts
Labels: Improvement

#595 style: code formatting
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .github/workflows/update-version.yml
Labels: CI

#597 fix: authorization in user currency
  .github/pull_request_template.md
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .github/workflows/update-version.yml
  src/interceptors/authorize.interceptor.ts
Labels: Improvement

#599 chore: bump version to 2.1.6
  package.json
  public/index.html
Labels: Feature

#600 fix: tipsBalanceInfo serverId
  src/controllers/walletaddress.controller.ts
Labels: Improvement

#601 cd: improve ingress
  .github/workflows/deployer.yml
Labels: CI

#602 ci: fix create tags & release
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: CI

#603 fix: update transaction
  src/controllers/transaction.controller.ts
Labels: Improvement

#604 feat: claim reference for network myriad
  package.json
  public/index.html
  src/controllers/claim-reference.controller.ts
  src/interfaces/transaction-summary.interface.ts
  src/services/network.service.ts
Labels: Feature

#606 fix: typo deletedAt on experience
  src/controllers/experience.controller.ts
Labels: Improvement

#598 fix: validate total experience created by user
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/interceptors/create.interceptor.ts
  src/services/experience.service.ts
Labels: Improvement

#607 fix: read all notifications
  src/controllers/notification.controller.ts
  src/interceptors/authorize.interceptor.ts
  src/services/notification.service.ts
Labels: Improvement

#608 fix: setInterval when verifying social media
  src/controllers/user-social-media.controller.ts
  src/models/user-verification.model.ts
Labels: Improvement

#609 fix: user counter when imported post
  src/interceptors/create.interceptor.ts
Labels: Improvement

#610 fix: change blockchain claim reference method
  src/services/network.service.ts
Labels: Improvement

#611 fix: added additional data for user experiences
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/interceptors/pagination.interceptor.ts
  src/interfaces/meta-pagination.interface.ts
Labels: Improvement

#596 fix: different image sizes for imported post
  package.json
  public/index.html
  src/__tests__/acceptance/post.acceptance.ts
  src/interceptors/create.interceptor.ts
  src/interfaces/asset.interface.ts
  src/services/social-media.service.ts
Labels: Improvement

#612 fix: include user currencies in user response
  src/controllers/wallet.controller.ts
  src/interceptors/find-by-id.interceptor.ts
  src/models/user-currency.model.ts
  src/models/user.model.ts
  src/repositories/user.repository.ts
Labels: Improvement

#613 fix: added new notification type
  src/enums/notification-type.enum.ts
  src/services/notification.service.ts
Labels: Improvement

#614 feat: airdrop onboard user
  src/__tests__/helpers/database.helper.ts
  src/interceptors/pagination.interceptor.ts
  src/models/people.model.ts
  src/models/transaction.model.ts
  src/repositories/people.repository.ts
  src/services/currency.service.ts
  src/services/fcm.service.ts
  src/services/notification.service.ts
  src/services/user-social-media.service.ts
Labels: Feature

#615 fix: added new field in server model
  package.json
  public/index.html
  src/controllers/server.controller.ts
  src/models/people.model.ts
  src/models/server.model.ts
  src/services/fcm.service.ts
  src/services/notification.service.ts
Labels: Improvement

#616 fix: fcm notification icon
  package.json
  src/services/fcm.service.ts
Labels: bug, Fix
