Repository myriadsocial/myriad-api, pull requests merged in 2022-01, with the labels that each got.

#342 MYR-1496: add new deployment env
  .github/workflows/deploy.yml
Labels: CI

#345 fixed report
  src/__tests__/acceptance/user-social-media.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/__tests__/integration/controllers/user-social-media.controller.integration.ts
  src/controllers/user-report.controller.ts
  src/services/post.service.ts
Labels: Improvement

#346 fixed kudos
  src/interceptors/validate-vote.interceptor.ts
Labels: Improvement

#348 improve open api & explorer disable
  .github/workflows/deploy.yml
Labels: CI

#347 activate auto claim tips
  src/interceptors/initial-creation.interceptor.ts
  src/services/currency.service.ts
  src/services/post.service.ts
Labels: Improvement

#349 fixed seach experience
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#350 fixed reports
  src/interceptors/report.interceptor.ts
Labels: Improvement

#351 fixed timeline response
  src/__tests__/integration/controllers/people.controller.integration.ts
  src/__tests__/unit/people.controller.unit.ts
  src/controllers/people.controller.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
  src/services/tag.service.ts
Labels: Improvement

#352 Use database connection string
  .env-template
  .github/workflows/deploy.yml
  src/config.ts
  src/datasources/mongo.datasource.ts
Labels: Improvement

#353 Fixed deployment database connection string
  .github/workflows/deploy.yml
Labels: Fix

#354 Fixed database connection string
  src/datasources/mongo.datasource.ts
Labels: Fix

#357 hotfix
  src/controllers/vote.controller.ts
  src/index.ts
  src/models/account-setting.model.ts
  src/models/draft-post.model.ts
  src/models/friend.model.ts
  src/models/notification-setting.model.ts
  src/models/user-social-media.model.ts
Labels: Improvement

#358 deactivate migration script
  src/application.ts
Labels: Improvement

#361 Added mongo protocol options
  .env-template
  .github/workflows/deploy.yml
  src/config.ts
  src/datasources/mongo.datasource.ts
Labels: Feature

#359 Fixed timeline by experience
  src/controllers/user-experience.controller.ts
  src/interceptors/experience.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
Labels: Fix

#362 Add priority field in currency collection
  src/__tests__/acceptance/user-currency.acceptance.ts
  src/controllers/user-currency.controller.ts
  src/interceptors/validate-currency.interceptor.ts
  src/models/user-currency.model.ts
  src/models/user.model.ts
  src/repositories/user.repository.ts
  src/services/experience.service.ts
Labels: Improvement

#363 Added new endpoint user currency
  src/__tests__/helpers/database.helper.ts
  src/controllers/user-currency.controller.ts
  src/interceptors/experience.interceptor.ts
  src/services/metric.service.ts
Labels: Improvement

#364 added indexes to improve query
  .github/workflows/deploy.yml
  src/models/activity-log.model.ts
  src/models/comment.model.ts
  src/models/experience.model.ts
  src/models/friend.model.ts
  src/models/leader-board.model.ts
  src/models/notification.model.ts
  src/models/post.model.ts
  src/models/tag.model.ts
  src/models/transaction.model.ts
  src/models/user-currency.model.ts
  src/models/user-experience.model.ts
  src/models/user-report.model.ts
  src/models/user-social-media.model.ts
  src/models/user.model.ts
  src/models/vote.model.ts
Labels: Improvement

#365 Clean code
  package.json
  public/index.html
  src/application.ts
  src/controllers/activity-log.controller.ts
  src/controllers/authentication.controller.ts
  src/controllers/comment.controller.ts
  src/controllers/currency.controller.ts
  src/controllers/deleted-collection.controller.ts
  src/controllers/exchange-rate.controller.ts
  src/controllers/experience.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/leader-board.controller.ts
  src/controllers/notification.controller.ts
  src/controllers/people.controller.ts
  src/controllers/post-walletaddress.controller.ts
  src/controllers/post.controller.ts
  src/controllers/queue.controller.ts
  src/controllers/report-user.controller.ts
  src/controllers/report.controller.ts
  src/controllers/storage.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tip.controller.ts
  src/controllers/transaction-summary.controller.ts
  src/controllers/transaction.controller.ts
  src/controllers/user-account-setting.controller.ts
  src/controllers/user-currency.controller.ts
  src/controllers/user-draft-post.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/user-notification-setting.controller.ts
  src/controllers/user-report.controller.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/user.controller.ts
  src/controllers/vote.controller.ts
  src/data-seed/.gitignore
  src/data-seed/README.md
  yarn.lock
Labels: Fix

#366 fixed timeline
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#367 fixed timeline
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#368 Leaderboard snapshot
  docs/airdrop/README.md
  docs/airdrop/leaderboard-snapshot.json
  docs/airdrop/leaderboard-snapshot.md
Labels: documentation

#369 Added airdrop status
  src/__tests__/helpers/database.helper.ts
  src/__tests__/integration/controllers/user.controller.integration.ts
  src/controllers/index.ts
  src/controllers/leader-board.controller.ts
  src/controllers/user.controller.ts
  src/enums/classname-type.enum.ts
  src/interceptors/initial-creation.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/migrations/0.0.0.migration.ts
  src/migrations/1.0.0.migration.ts
  src/models/index.ts
  src/models/leader-board.model.ts
  src/models/user.model.ts
  src/repositories/index.ts
  src/repositories/leader-board.repository.ts
  src/repositories/user.repository.ts
  src/services/activity-log.service.ts
  src/services/metric.service.ts
Labels: Feature

#372 Add node selector
  .github/workflows/deploy.yml
Labels: CI

#373 Created migration script
  src/application.ts
  src/migrate.ts
Labels: Improvement

#374 Fixed experience filter
  src/services/experience.service.ts
Labels: Improvement

#375 Added new field in platform post model
  src/controllers/post.controller.ts
  src/models/platform-post.model.ts
Labels: Improvement

#378 Added airdrop functionality
  package.json
  src/airdrop.ts
  src/utils/polkadotJs-utils.ts
  yarn.lock
Labels: Feature

#379 Added language setting
  src/__tests__/helpers/database.helper.ts
  src/application.ts
  src/controllers/index.ts
  src/controllers/user-language-setting.controller.ts
  src/interceptors/initial-creation.interceptor.ts
  src/migrate.ts
  src/models/index.ts
  src/models/language-setting.model.ts
  src/models/user.model.ts
  src/repositories/index.ts
  src/repositories/language-setting.repository.ts
  src/repositories/user.repository.ts
Labels: Feature

#380 fixed migration
  package.json
  src/application.ts
  src/enums/notification-type.enum.ts
  src/migrations/0.0.0.migration.ts
  src/migrations/1.0.0.migration.ts
  src/migrations/README.md
  src/services/currency.service.ts
  yarn.lock
Labels: Improvement

#381 Added doc airdrop leaderboard distribution
  docs/airdrop/README.md
  docs/airdrop/leaderboard-distribution.md
Labels: Document

#382 Added doc airdrop leaderboard distribution
  docs/airdrop/README.md
  docs/airdrop/leaderboard-distribution.md
  docs/airdrop/leaderboard-distribution.txt
  src/airdrop.ts
Labels: Document

#383 Added doc airdrop leaderboard distribution
  docs/.gitkeep
  docs/airdrop/README.md
Labels: Document

#384 Remove ingress staging, testnet, mainnet
  .github/workflows/deploy.yml
  docs/airdrop/README.md
Labels: CI

#343 Created migration script
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/post.acceptance.ts
  src/__tests__/acceptance/user-currency.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/controllers/comment.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/report.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/user-social-media.controller.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/post.service.ts
  src/services/social-media.service.ts
Labels: Improvement

#386 Implement private account in timeline
  src/__tests__/acceptance/post.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/interceptors/pagination.interceptor.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/experience.service.ts
  src/services/friend.service.ts
Labels: Improvement

#387 Added total reply comment in comment metric
  src/interceptors/authorize.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/models/comment.model.ts
  src/services/metric.service.ts
  src/services/vote.service.ts
Labels: Improvement

#389 Removed limit nested comment
  .env-template
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
  src/__tests__/acceptance/comment.acceptance.ts
  src/application.ts
  src/config.ts
  src/index.ts
  src/interceptors/create.interceptor.ts
Labels: Improvement

#390 Fixed get users including private account
  src/interceptors/pagination.interceptor.ts
  src/services/friend.service.ts
Labels: Fix

#391 Added function to remove all related post
  src/__tests__/acceptance/post.acceptance.ts
  src/interceptors/report.interceptor.ts
  src/services/notification.service.ts
  src/services/post.service.ts
Labels: Improvement

#392 Added analyzer workflow
  .github/workflows/analyzer.yml
  .github/workflows/deployer.yml
  .prettierignore
  src/interceptors/create.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/social-media.service.ts
Labels: CI

#393 Handle demo version
  src/__tests__/acceptance/friend.acceptance.ts
  src/controllers/activity-log.controller.ts
  src/controllers/comment.controller.ts
  src/controllers/currency.controller.ts
  src/controllers/exchange-rate.controller.ts
  src/controllers/experience.controller.ts
  src/controllers/friend.controller.ts
  src/controllers/notification.controller.ts
  src/controllers/people.controller.ts
  src/controllers/post-walletaddress.controller.ts
  src/controllers/post.controller.ts
  src/controllers/queue.controller.ts
  src/controllers/report-user.controller.ts
  src/controllers/report.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tip.controller.ts
  src/controllers/transaction-summary.controller.ts
  src/controllers/transaction.controller.ts
  src/controllers/user-account-setting.controller.ts
  src/controllers/user-currency.controller.ts
  src/controllers/user-draft-post.controller.ts
  src/controllers/user-experience.controller.ts
  src/controllers/user-language-setting.controller.ts
  src/controllers/user-notification-setting.controller.ts
  src/controllers/user-social-media.controller.ts
  src/controllers/user.controller.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/notification.service.ts
  src/services/post.service.ts
Labels: Improvement

#394 Fixed import post
  src/controllers/post.controller.ts
Labels: Fix

#396 Fixed parsing text for twitter
  src/services/social-media.service.ts
Labels: Fix

#397 Fixed post counter
  src/services/metric.service.ts
Labels: Fix

#398 Fixed parsing text for twitter
  src/services/social-media.service.ts
Labels: Fix

#399 Fixed timeline
  src/__tests__/integration/services/reddit.service.integration.ts
  src/controllers/people.controller.ts
  src/controllers/post.controller.ts
  src/controllers/user.controller.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/notification.service.ts
  src/services/post.service.ts
Labels: Improvement
