Repository myriadsocial/myriad-api, pull requests merged in 2022-03, with the labels that each got.

#463 Fixed private experience
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/controllers/user-experience.controller.ts
  src/interceptors/find-by-id.interceptor.ts
  src/services/experience.service.ts
Labels: Improvement

#464 Added verified field in user model
  src/application.ts
  src/controllers/authentication.controller.ts
  src/controllers/user.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/models/user.model.ts
Labels: Improvement

#467 Fixed timeline
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#468 Rearrange enum constant
  src/controllers/index.ts
  src/datasources/index.ts
  src/enums/activity-log-type.enum.ts
  src/enums/controller-type.enum.ts
  src/enums/friendstatus-type.enum.ts
  src/enums/index.ts
  src/enums/method-type.enum.ts
  src/enums/notification-type.enum.ts
  src/enums/permission-keys.enum.ts
  src/enums/platform-type.enum.ts
  src/enums/reference-type.enum.ts
  src/enums/report-status-type.enum.ts
  src/enums/report-type.enum.ts
  src/enums/timelinefilter-type.enum.ts
  src/enums/visibility-type.enum.ts
  src/interceptors/index.ts
  src/interfaces/index.ts
  src/jobs/index.ts
  src/models/index.ts
  src/repositories/index.ts
  src/services/index.ts
Labels: Improvement

#469 Fixed experience query
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#466 Include post in comment collection
  src/__tests__/acceptance/comment.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/models/comment.model.ts
  src/repositories/comment.repository.ts
  src/services/vote.service.ts
Labels: Improvement

#470 Feature delete comment
  src/__tests__/acceptance/comment.acceptance.ts
  src/__tests__/unit/comment.controller.unit.ts
  src/controllers/comment.controller.ts
  src/interceptors/delete.interceptor.ts
  src/models/comment.model.ts
Labels: Feature

#471 Fixed comment delete by user
  src/__tests__/acceptance/user-currency.acceptance.ts
  src/application.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
Labels: Improvement

#474 Optimize deployment resource request & limit
  .github/workflows/deployer.yml
Labels: CI

#473 Fixed experience timeline
  src/__tests__/acceptance/comment.acceptance.ts
  src/__tests__/acceptance/post.acceptance.ts
  src/application.ts
  src/controllers/experience-post.controller.ts
  src/controllers/people.controller.ts
  src/controllers/post.controller.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/interceptors/report.interceptor.ts
  src/interceptors/validate-post-import-url.interceptor.ts
  src/models/post.model.ts
  src/services/experience.service.ts
  src/services/metric.service.ts
  src/services/post.service.ts
  src/services/user-social-media.service.ts
Labels: Improvement

#475 Fixed count comment
  src/__tests__/acceptance/currency.acceptance.ts
  src/interceptors/report.interceptor.ts
Labels: Improvement

#476 Added deletedAt in people
  src/controllers/user-social-media.controller.ts
  src/interceptors/find-by-id.interceptor.ts
  src/services/experience.service.ts
  src/services/user-social-media.service.ts
Labels: Improvement

#477 Fixed recounting comment when delete by user
  src/__tests__/acceptance/comment.acceptance.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/delete.interceptor.ts
  src/models/comment.model.ts
  src/services/metric.service.ts
  src/services/vote.service.ts
Labels: Improvement

#478 Fixed user network endpoint
  src/controllers/user-network.controller.ts
Labels: Improvement

#479 Handle authentication when getting user wallet
  src/services/authentication/jwt.auth.strategy.ts
Labels: Improvement

#480 Fix post wallet address
  src/__tests__/acceptance/post-walletaddress.acceptance.ts
  src/controllers/post-walletaddress.controller.ts
  src/services/authentication/jwt.auth.strategy.ts
Labels: Improvement

#481 Fixed transaction
  src/__tests__/acceptance/transaction.acceptance.ts
  src/interceptors/authorize.interceptor.ts
Labels: Improvement

#482 fix github workflow setup gcloud step
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
  .gitignore
Labels: CI

#483 Google auth with workload identity federation
  .github/workflows/deployer.yml
Labels: CI

#484 add jobs permission
  .github/workflows/deployer.yml
Labels: CI

#485 Bump version 2.0.0
  package.json
  public/index.html
Labels: Improvement

#486 Fixed endpoints
  src/controllers/user-network.controller.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/update.interceptor.ts
Labels: Improvement

#487 Fixed primary wallet
  .github/workflows/mlc_config.json
  src/__tests__/acceptance/user-wallet.acceptance.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
Labels: Improvement

#488 Fixed connect network
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/controllers/authentication.controller.ts
  src/controllers/user-network.controller.ts
  src/controllers/user-wallet.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/interceptors/update.interceptor.ts
  src/models/wallet.model.ts
  src/services/authentication/jwt.service.ts
Labels: Improvement

#489 Fixed change network
  src/interceptors/update.interceptor.ts
Labels: Improvement
