Repository myriadsocial/myriad-api, pull requests merged in 2022-11, with the labels that each got.

#670 cd: improve ci/cd
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: Improvement

#672 fix: added flagging for lite version
  src/controllers/authentication.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/create.interceptor.ts
  src/models/user.model.ts
  src/services/authentication/jwt.auth.strategy.ts
Labels: Improvement

#674 fix: revalidate OTP
  src/models/user-otp.model.ts
  src/services/user-otp.service.ts
Labels: Fix

#673 fix: set limitation for lite version
  src/__tests__/acceptance/friend.acceptance.ts
  src/__tests__/acceptance/user-experience.acceptance.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/create.interceptor.ts
Labels: Improvement

#675 feat: edit email
  src/application.ts
  src/controllers/admin.controller.ts
  src/controllers/claim-reference.controller.ts
  src/controllers/index.ts
  src/controllers/user/index.ts
  src/controllers/user/setting.controller.ts
  src/enums/method-type.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/models/change-email-request.model.ts
  src/models/index.ts
  src/models/user-otp.model.ts
  src/models/user.model.ts
  src/repositories/change-email-request.repository.ts
  src/repositories/index.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/user-otp.service.ts
  src/services/user.service.ts
Labels: Feature, Improvement

#676 fix: set limit on create post, import post, and comment
  src/__tests__/acceptance/comment.acceptance.ts
  src/__tests__/acceptance/post.acceptance.ts
  src/interceptors/create.interceptor.ts
Labels: Improvement

#678 fix: added remove email endpoint
  src/controllers/user/setting.controller.ts
  src/services/authentication/jwt.auth.strategy.ts
  src/services/user-otp.service.ts
  src/services/user.service.ts
Labels: Improvement

#679 fix: removed add myriad as friend
  src/interceptors/authentication.interceptor.ts
  src/models/user.model.ts
  src/services/friend.service.ts
  src/utils/formatted.ts
Labels: Improvement

#680 fix: connect wallet in lite version
  src/interceptors/create.interceptor.ts
Labels: Improvement

#681 fix: unlimited subscribe experience
  src/interceptors/create.interceptor.ts
  src/utils/formatted.ts
Labels: Improvement

#682 fix: extend timeout time
  src/interceptors/create.interceptor.ts
  src/models/experience.model.ts
  src/services/user-otp.service.ts
Labels: Improvement

#683 fix: remove required people on create experiences
  package.json
  src/interceptors/create.interceptor.ts
  src/interceptors/update.interceptor.ts
Labels: Improvement

#685 chore: bump version to 2.2.0
  package.json
Labels: Improvement

#687 fix: refactor login flow by email
  src/__tests__/helpers/given-instances.ts
  src/controllers/authentication.controller.ts
  src/interceptors/authentication.interceptor.ts
  src/models/request-create-new-user-by-email.model.ts
  src/models/user.model.ts
  src/repositories/index.ts
  src/repositories/request-create-new-user-by-email.repository.ts
  src/services/user-otp.service.ts
Labels: Improvement

#688 fix: changed signup by email response
  src/controllers/authentication.controller.ts
Labels: Improvement

#689 fix: remove exchange rates job
  src/application.ts
Labels: Improvement

#690 fix: fixed update email
  src/controllers/user/setting.controller.ts
  src/models/user.model.ts
  src/services/user.service.ts
Labels: Improvement

#691 fix: dump mongo connector to 6.1.0
  .maintain/docker/Dockerfile
  package.json
  src/interceptors/authentication.interceptor.ts
  src/services/notification.service.ts
  src/utils/url-utils.ts
  yarn.lock
Labels: CI

#692 fix: renamed class name
  src/__tests__/integration/controllers/friend.controller.integration.ts
  src/__tests__/integration/controllers/notification.controller.integration.ts
  src/__tests__/integration/controllers/transaction.controller.integration.ts
  src/config.ts
  src/controllers/statistic.controller.ts
  src/controllers/user/claim-reference.controller.ts
  src/controllers/user/comment.controller.ts
  src/controllers/user/friend.controller.ts
  src/controllers/user/notification.controller.ts
  src/controllers/user/post.controller.ts
  src/controllers/user/setting.controller.ts
  src/controllers/user/transaction.controller.ts
  src/controllers/user/vote.controller.ts
  src/controllers/user/wallet.controller.ts
  src/enums/controller-type.enum.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/pagination.interceptor.ts
  src/services/metric.service.ts
  src/services/user.service.ts
Labels: Improvement

#695 feat: total email on server matric
  src/interfaces/metric.interface.ts
  src/services/metric.service.ts
Labels: Feature

#696 fix: fixed add email
  src/services/user-otp.service.ts
Labels: Improvement

#697 chore: bump version to 2.2.1
  package.json
Labels: Improvement

#698 fix: rename endpoint for reference walletaddress
  src/__tests__/acceptance/walletaddress.acceptance.ts
  src/controllers/wallet-address.controller.ts
  src/services/authentication/jwt.auth.strategy.ts
Labels: Improvement

#694 fix: refactor phase 2
  src/__tests__/acceptance/authentication.acceptance.ts
  src/__tests__/acceptance/comment.acceptance.ts
  src/__tests__/acceptance/user.acceptance.ts
  src/__tests__/helpers/database.helper.ts
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/controllers/auth/admin.controller.ts
  src/controllers/auth/authentication.controller.ts
  src/controllers/auth/index.ts
  src/controllers/authentication.controller.ts
  src/controllers/index.ts
  src/controllers/tag.controller.ts
  src/controllers/user/user.controller.ts
  src/enums/controller-type.enum.ts
  src/enums/method-type.enum.ts
  src/interceptors/authentication.interceptor.ts
  src/interceptors/authorize.interceptor.ts
  src/interceptors/find-by-id.interceptor.ts
  src/interceptors/index.ts
  src/interceptors/pagination.interceptor.ts
  src/models/comment.model.ts
  src/models/credential.model.ts
  src/models/friend.model.ts
  src/models/post.model.ts
  src/models/user.model.ts
  src/services/admin.service.ts
  src/services/authentication/auth.service.ts
  src/services/authentication/index.ts
  src/services/currency.service.ts
  src/services/experience.service.ts
  src/services/filter-builder.service.ts
  src/services/friend.service.ts
  src/services/index.ts
  src/services/metric.service.ts
  src/services/tag.service.ts
  src/services/transaction.service.ts
  src/services/user.service.ts
  src/utils/formatter.ts
Labels: Improvement

#701 fix: renamed authentication endpoint
  src/__tests__/acceptance/authentication.acceptance.ts
  src/controllers/authentication.controller.ts
  src/services/authentication/auth.service.ts
Labels: Improvement

#704 fix: user wallet filter
  src/services/filter-builder.service.ts
Labels: Improvement

#705 feat: selected user visibility on post and experience
  src/enums/visibility-type.enum.ts
  src/interceptors/authorize.interceptor.ts
  src/models/experience.model.ts
  src/models/post.model.ts
  src/services/filter-builder.service.ts
  src/services/post.service.ts
  src/services/user-experience.service.ts
Labels: Feature

#706 fix: login by wallet
  src/services/authentication/auth.service.ts
Labels: Improvement
