Repository myriadsocial/myriad-api, pull requests merged in 2023-02, with the labels that each got.

#757 fix: include instance id on server seed data
  seed-data/server.json
  src/__tests__/acceptance/unlockable-content.acceptance.ts
  src/__tests__/helpers/given-instances.ts
  src/application.ts
  src/models/server.model.ts
  src/services/wallet-address.service.ts
Labels: Improvement

#758 fix: data seed
  .env-template
  .gitignore
  package.json
  seed-data/assets/near.png
  seed-data/default-network-currencies.json
  seed-data/default-user-wallet.json
  seed-data/server.json
  src/application.ts
  src/config.ts
  src/models/server.model.ts
  src/models/user.model.ts
  src/utils/upload.ts
Labels: Fix

#766 fix: update post created at when add post to experience
  src/services/experience.service.ts
Labels: Improvement

#767 fix: fixed average calculation
  src/services/statistic.service.ts
Labels: Improvement

#768 fix: handle added post to timeline
  src/services/experience.service.ts
  src/services/post.service.ts
Labels: Improvement

#770 fix: included total amount on exlusive content
  src/interceptors/pagination.interceptor.ts
Labels: Improvement

#771 fix: update reference id when fetch wallet address
  src/services/wallet-address.service.ts
Labels: Improvement

#772 fix: handle claim reference of a big number
  src/services/network.service.ts
  src/services/post.service.ts
  src/services/wallet-address.service.ts
Labels: Improvement

#773 fix: improve auth response when login
  src/controllers/authentication.controller.ts
  src/interfaces/token.inteface.ts
  src/services/authentication/auth.service.ts
Labels: Improvement

#774 fix: update order filter
  src/models/imported-post.model.ts
  src/models/post.model.ts
  src/services/filter-builder.service.ts
Labels: Improvement

#775 fix: update order filter on post
  src/services/filter-builder.service.ts
Labels: Improvement

#780 fix: handle filter post query
  src/__tests__/acceptance/post.acceptance.ts
  src/models/experience.model.ts
  src/services/filter-builder.service.ts
  src/services/post.service.ts
  src/services/user-experience.service.ts
Labels: Improvement

#781 fix: improved post filter query
  src/services/filter-builder.service.ts
Labels: Improvement

#790 chore(main): release 2.3.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
