Repository myriadsocial/myriad-api, pull requests merged in 2023-04, with the labels that each got.

#832 fix: timeline filter for single experience
  src/services/filter-builder.service.ts
Labels: Improvement

#833 fix: experience find
  src/controllers/experience/experience.controller.ts
  src/enums/method-type.enum.ts
  src/interceptors/pagination.interceptor.ts
  src/services/experience.service.ts
  src/services/filter-builder.service.ts
Labels: Fix

#834 fix: find by createdby
  src/services/filter-builder.service.ts
Labels: Fix

#835 fix: expirience
  src/__tests__/helpers/database.helper.ts
  src/controllers/experience/post.controller.ts
  src/enums/user-experience-status.enum.ts
  src/models/user-experience.model.ts
  src/services/experience.service.ts
Labels: Feature

#838 fix: handle empty selectedTimelineIds when creating post
  src/__tests__/helpers/database.helper.ts
  src/services/post.service.ts
Labels: Improvement

#844 fix: timeline filter
  src/services/filter-builder.service.ts
Labels: Improvement

#848 fix: date format when update user experience
  src/services/experience.service.ts
  src/services/filter-builder.service.ts
Labels: Improvement

#849 fix: improve timeline query
  src/application.ts
  src/models/timeline-config.model.ts
  src/services/filter-builder.service.ts
Labels: Improvement

#856 fix: resolve filter query on search timeiline
  src/services/filter-builder.service.ts
  src/services/post.service.ts
Labels: Improvement

#857 fix: resolve create post
  src/services/post.service.ts
Labels: Improvement
